version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rrhh-backend:latest
    container_name: rrhh_app_prod
    restart: unless-stopped
    ports:
      - "3004:3004"
    env_file:
      - .env              # archivo local con DATABASE_URL, PORT, JWT_SECRET, etc.
    environment:
      - PORT=3004         # override si quieres forzar 3004
    # no depend_on porque la DB es externa
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
